#! /bin/bash

url="$1"  # Must be before bash's read command
read -p 'Download video portion? (y/n): ' -r video;
[ "$video" == "n" ] && read -p 'Play audio with termux-media-player? (y/n): ' -r mplayer;

curl -L --proto '=https' --tlsv1.2 -sSf \
    https://raw.githubusercontent.com/joectchan/ytdl/master/cfg/run.sh \
    | bash -s -- PLACEHOLDERNAME "$url" "$video" "$mplayer";
    
read -p 'Debug: back to url-opener' -r junk;
echo 'Debug: Play audio with termux-media-player? $mplayer'
read -p 'Debug: hard code to use cplay-ng at ~/storage/external-1/music' -r junk;
cd ~/storage/external-1/music; cplay-ng
